#!/usr/bin/env python
 
# some original codes we need
import os
 
virtenv = os.environ['OPENSHIFT_HOMEDIR'] + 'python2.7/virtenv/'
#os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
os.environ['PYTHON_EGG_CACHE'] = '/tmp'
#virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
#try:
#    execfile(virtualenv, dict(__file__=virtualenv))
#except:
#    pass
 
# new codes we adding for Django
import sys
import django.core.handlers.wsgi
 
os.environ['DJANGO_SETTINGS_MODULE'] = os.environ['OPENSHIFT_APP_NAME']+'.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi' ))
application = django.core.handlers.wsgi.WSGIHandler()
